on:
  push:
    branches:
    - main
    tags: ['v*.*.*']
 #, windows-latest, macOS-latest]
jobs:
  my_job:

    strategy:
      matrix:
        include:
        - os: windows-latest
          target: x86_64-pc-windows-msvc
          code-target: win32-x64
          bin-ext: .exe
        - os: windows-latest
          target: i686-pc-windows-msvc
        - os: windows-latest
          target: aarch64-pc-windows-msvc
          code-target: win32-arm64
        - os: ubuntu-20.04
          target: x86_64-unknown-linux-gnu
          code-target: linux-x64
        - os: ubuntu-20.04
          target: aarch64-unknown-linux-gnu
          code-target: linux-arm64
        - os: ubuntu-20.04
          target: arm-unknown-linux-gnueabihf
          code-target: linux-armhf
        - os: macos-12
          target: x86_64-apple-darwin
          code-target: darwin-x64
        - os: macos-12
          target: aarch64-apple-darwin
          code-target: darwin-arm64

    name: dist (${{ matrix.target }})
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Rust toolchain
      run: |
        # rustup update --no-self-update stable
        rustup default nightly
        rustup target add ${{ matrix.target }}
        
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        
    - name: Install Node Dependencies
      run: npm ci

    - name: Cargo Build
      working-directory: server
      run: cargo build --release --target ${{ matrix.target }}

    - name: Move language server binary
      run: |
        mv server/target/${{ matrix.target }}/release/owl-ms-language-server${{ matrix.bin-ext }} server/owl-ms-language-server${{ matrix.bin-ext }}

    - name: Publish on OVSX
      run: npx ovsx publish --pat ${{ secrets.PAT_OVSX }} --target ${{ matrix.code-target }}

    - name: Publish on VSCE
      run: npx vsce publish --pat ${{ secrets.PAT_VSCE }} --target ${{ matrix.code-target }}
